### ISSUE TITLE
Support for Hiding the '+' on the Add Button

### ISSUE THREAD

**Issue by V-FEXrt** [joncardasis/ChromaColorPicker#10]
Looking at the ChromaAddButton it would be really easy to hide the '+' button (which is functionality I would like/need) but I was wondering how you would like that added as it may affect the public API. 

If you would prefer to not have this added, I will likely just add it to my personal fork.

**Comment by joncardasis** [comment]
You should be able to set the opacity on the component to zero (or use .hidden for views) and it should work just fine. Some sizes are based on it so hiding it rather than removing is your best option. The subcomponents (subviews/sublayers) can all be seen in the README and you can hide what you like

**Comment by V-FEXrt** [comment]
Oh yeah. I didn't think about that. Thanks.
