### ISSUE TITLE
How to pick a color with alpha value?

### ISSUE THREAD

**Issue by ifanchu** [joncardasis/ChromaColorPicker#23]
I must be missing something but I couldn't find where I can set the alpha. 
Please advise.

**Comment by joncardasis** [comment]
The control does not have support for alphas. I would suggest creating another slider to do this. You can reuse the `ChromaShadeSlider` if you want to mimic the style

**Comment by mrvallejo** [comment]
I am trying to reuse the ChromaShadeSlider for changing alpha instead of the color. Could you give us some code for replacing in the ChromaShadeSlider for this purpose? Thanks!

**Comment by joncardasis** [comment]
@mrvallejo It wouldn't take much work. Not sure how you imagine the slider to display alpha values, but ChromeShadeSlider's `currentColor: UIColor` should just use `primaryColor.colorWithAlphaValue(...)` instead of the current `.darkerColor()` and `.lighterColor()`. Note that you'd use a modified version of `currentValue` as the alpha value since `currentValue` has a range of [-1,1]. Therefore you'd use `alpha = (currentValue + 1)/2` to determine the alpha value from the position of the slider. Hope this gets you started.

**Comment by joncardasis** [comment]
I am starting a rewrite of a number of features on this project for better customizability. If you have any suggestions you'd like to see in the evolution of this project, please open a new issue with the `EVOLUTION REQUEST` label.
