### ISSUE TITLE
Shades of gray not supported?

### ISSUE THREAD

**Issue by rogomantik** [joncardasis/ChromaColorPicker#3]
Shades of gray not supported?

**Comment by Laptopmini** [comment]
+1

**Comment by V-FEXrt** [comment]
@joncardasis Ideally this is something I would like to have as well. Maybe it is something we can work on together?

**Comment by joncardasis** [comment]
I've played with the idea before (I'm just getting to maintaining some older projects atm like this one). I'm curious of how shades of gray could be supported with the current design of the control since the ring is based on hue and the slider is based on intensity and blends between black and white.

The picker should be able to select a gray color `rgba(0.5, 0.5, 0.5, 1)` and then the shader could take care of the spectrum between gray and black and gray and white respectively.

@V-FEXrt One idea I came up with is this:
![idea](http://i.imgur.com/JvfSfbb.png)

When the handle is lifted up and if a `supportsShadesOfGray: Bool` property is true, then the middle plus button will become gray, the plus will disappear and the handle can move freeform within the bounds of the circle. (Since color is based on the angle from the center point this could still work) 

If the handle is moved to the center button (using [CGRects contains(_ :) method](https://developer.apple.com/documentation/coregraphics/cgrect/1454186-contains)) the handle color changes to gray and if let go it will go back to the original lifted space on the circle and become gray. The shade slider would work just fine from there.

This would require quite a bit of rework as to how the control functions and making sure everything 'snaps' into place.

@V-FEXrt how does this appeal to you? Any suggestions are welcome 😸

**Comment by joncardasis** [comment]
Sitting on the idea I found one I think I'll be implementing soon.

![possible-solution](http://i.imgur.com/zh4I7rU.png)

What I am now planning to do:
- Add a `public var supportsShadesOfGray: Bool` property
- When `supportsShadesOfGray` is true a toggle indicator will appear in the upper left of the control
- This toggle indicator will be gray when the picker is in "hue mode" and when tapped, will turn to an arbitrary color and the picker will switch to "grayscale mode"

This way it is optional to implement, minimal effort, doesn't break the current design pattern, and allows for shades of gray.

**Comment by V-FEXrt** [comment]
Hmm, I really like the first suggestion, but the second one seems more reasonable, and perfectly acceptable for what I need. Is there anything in the implementation that you would like me to help with?

**Comment by joncardasis** [comment]
@V-FEXrt  Take a look at https://github.com/joncardasis/ChromaColorPicker/tree/grayscale. I whipped something up. I'll test and merge to master hopefully tomorrow 👍

**Comment by joncardasis** [comment]
I am closing this issue as gray shades are now supported :)

**Comment by V-FEXrt** [comment]
Looks great!
